config/routes.rb
Rails.application.routes.draw do
  
	root "home#index"
	
	devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
	resources :news
	resources :routes do
		resources :waypoints
	end

	get '/filter', to: 'routes#filter', as: 'filter_routes'
  
end

app/models/new.rb
class New < ActiveRecord::Base
end

app/models/route.rb
class Route < ActiveRecord::Base
	has_many :waypoints

	def self.filterDifficulty(difficulty)
		self.where("difficulty = ?", difficulty)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
	belongs_to :route
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	news_index_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	def index
		
	end
	
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

	def index
		@routes = Route.all

		respond_to do |format|
			format.html #index.html.erb
	      	format.json { render json: {:route => @routes } }
		end
	end

	def show
		@route = Route.find(params[:id])
		@waypoints = @route.waypoints

		respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: {:route => @route, :waypoints => @waypoints} }
   		end
	end

	def filter
		@routes = Route.where("difficulty = ?", params[:difficulty])
	
		respond_to do |format|
			format.html #index.html.erb
	      	format.json { render json: {:route => @routes } }
		end
	end
	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/home/index.html.erb
<%= render "partials/register" %>
<%= render "partials/log_in" %>

<header>
	<div class="container">
        <div class="row">
        	
		</div>
	</div>
</header>

<footer class="container-fluid">
	<div class="row div-footer">
		Copyright © Keep Running 2015 - All right reserved. Design & Developed by: Manuel Ábalos Serrano.
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keep Running</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link  rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">
  <link href='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css' rel='stylesheet' />
  <link href="http://api.tiles.mapbox.com/mapbox.js/v1.0.2/mapbox.css" rel="stylesheet" />
  <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.4/leaflet.fullscreen.css' rel='stylesheet' />
  <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
  <link rel='stylesheet' href='https://api.mapbox.com/mapbox.js/plugins/mapbox-directions.js/v0.3.0/mapbox.directions.css' type='text/css' />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "partials/navigation" %>

<%= yield %>

  <script src='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js'></script>
	<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.4/Leaflet.fullscreen.min.js'></script>
  <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
  <script src='https://api.mapbox.com/mapbox.js/plugins/mapbox-directions.js/v0.3.0/mapbox.directions.js'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/news/index.html.erb
<div class="container-fluid">
	<div class="row background-base">
		<%= render "partials/div_left" %>
		<div class="col-md-10 div-basic-right">
			<div class="row div-new">
				<img src="http://lorempixel.com/800/200" alt="..." class="img-thumbnail img-center">
				<h4 class="text-center title-header"><b>Titulo header - 1<b></h4>
				<p class="text-header">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet ex. Cras non ante feugiat, vulputate mi a, auctor neque. Fusce velit diam, hendrerit efficitur gravida ac, pretium sit amet mauris. Sed egestas, purus in lacinia sollicitudin.</p>
			</div>

			<div class="row">
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
				<div class="col-xs-6 col-md-3 div-new">
					<hr>
					<img src="http://lorempixel.com/200/125" alt="..." class="img-thumbnail img-center">
					<h4 class="text-center title-new"><b>Titulo header - X<b></h4>
					<p class="text-new">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada velit vitae mauris suscipit, ut dignissim felis eleifend. Sed tempor nisi velit, eget cursus nibh tempor et. Pellentesque fringilla imperdiet.</p>
					<hr>
				</div>
			</div>

			<div class="row">
				<nav>
				  <ul class="pager">
				    <li><a class="pager-li" href="#"><< Previous</a></li>
				    <li><a class="pager-li" href="#">Next >></a></li>
				  </ul>
				</nav>
			</div>
		</div>
	</div>
</div>

app/views/partials/_div_left.html.erb
<div class="col-md-2 hidden-xs div-basic-left">
	
	<div class="row">
		<div class="col-md-12 div-profile-avatar">
			<img src="http://lorempixel.com/150/150" alt="..." class="img-circle img-center">
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 div-profile-name">
			Manuel Ábalos Serrano
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 div-profile-stars">
			<img src="../stars/4.png" alt="..." class="img img-stars">
		</div>
	</div>
	<div class="row div-profile-level-experience">
		<div class="col-md-5">
			<b>Nivel:</b> 79
		</div>
		<div class="col-md-7">
			<b>Exp:</b> 890/1000
		</div>
	</div>

	<div class="row div-profile-panel">
		<div class="col-md-10 col-md-offset-1 div-profile-panel-button">
			Perfil
		</div>
	</div>

</div>

app/views/partials/_log_in.html.erb
<div class="modal fade bs-entrar-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-entrar">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Entrar</h4>
        </div>
      	<div class="modal-body">
      		<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
				<div class="field">
					<%= f.label :Correo_electronico %><br />
					<%= f.email_field :email, autofocus: true, placeholder: "Introduce su correo electrónico" %>
				</div>

				<div class="field">
					<%= f.label :Contraseña %><br />
					<%= f.password_field :password, autocomplete: "off", placeholder: "Introduce su contraseña" %>
				</div>

				<% if devise_mapping.rememberable? -%>
					<div class="field">
					  <%= f.check_box :remember_me %>&nbsp;&nbsp;<%= f.label :Recordar_contraseña %>
					</div>
				<% end -%>

				<div class="actions">
					<%= f.submit "Entrar", class: "btn btn-primary btn-modal-log-in" %>
					<button type="button" disabled class="btn btn-info btn-modal-facebook"><i class='fa fa-facebook-official fa-lg'></i>&nbsp;&nbsp;Accede con Facebook</button>
					<button type="button" disabled class="btn btn-info btn-modal-google"><i class='fa fa-google-plus-square fa-lg'></i>&nbsp;&nbsp;Accede con Google+</button>
				</div>
			<% end %>

			<%# render "devise/shared/links" %>

        	<p class="notice"><%# notice %></p>
	        <p class="alert"><%# alert %></p>
        </div>
    </div>
  </div>
</div>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><img class="img img-responsive img-navbar-logo" width="175px" src="../logoKeepRunning.png"/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav menu-superior">
            <li class="text-center">
              <a href="<%= news_index_path %>"><i class="menu-icon fa fa-lg fa-newspaper-o"></i>Noticias</a>
            </li>
            <li class="text-center">
              <a href="#"><i class="menu-icon fa fa-lg fa-user"></i>Perfil</a>
            </li>
            <li class="text-center">
              <a href="<%= routes_path %>"><i class="menu-icon fa fa-lg fa-street-view"></i>Rutas</a>
            </li>
            <li class="text-center">
              <a href="#"><i class="menu-icon fa fa-lg fa-heartbeat"></i>Entrenamiento</a>
            </li>
            <li class="text-center">
              <a href="#"><i class="menu-icon fa fa-lg fa-users"></i>Clasificación</a>
            </li>
            
        </ul>
        <ul class="nav navbar-nav navbar-right menu-superior">
            <li class="text-center"><%= link_to destroy_user_session_path, method: :delete do %><i class="menu-icon fa fa-lg fa-sign-out"></i>Cerrar Sesión<% end %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#" data-toggle="modal" data-target=".bs-registrar-modal-sm">Registrarse</a></li>
            <li><a href="#" data-toggle="modal" data-target=".bs-entrar-modal-sm">Entrar</a></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_register.html.erb
<div class="modal fade bs-registrar-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	<div class="modal-dialog" role="document">
	    <div class="modal-content modal-registrarse">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title text-center" id="myModalLabel">Registrate</h4>
	      </div>
	      <div class="modal-body">

							<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
								<%= devise_error_messages! %>

								<div class="field">
									<%= f.label :Correo_electrónico %><br />
									<%= f.email_field :email, autofocus: true , placeholder: "Introduce su correo electrónico" %>
								</div>

								<div class="field">
									<%= f.label :Contraseña %>
									<% if @minimum_password_length %>
										<em>(<%= @minimum_password_length %> characters minimum)</em>
									<% end %><br />
									<%= f.password_field :password, autocomplete: "off", placeholder: "Introduce su contraseña" %>
								</div>

								<div class="field">
									<%= f.label :Confirmar_contraseña %><br />
									<%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Introduce de nuevo su contraseña" %>
								</div>

								<div class="actions">
									<%= f.submit "Enviar", class: "btn btn-primary btn-modal-sign-up" %>
									<button type="button" disabled class="btn btn-info btn-modal-facebook"><i class='fa fa-facebook-official fa-lg'></i>&nbsp;&nbsp;Accede con Facebook</button>
									<button type="button" disabled class="btn btn-info btn-modal-google"><i class='fa fa-google-plus-square fa-lg'></i>&nbsp;&nbsp;Accede con Google+</button>
								</div>
								
							<% end %>

							<%# render "devise/shared/links" %>
							<div class="modal-footer">
					        	<p class="notice"><%# notice %></p>
					        	<p class="alert"><%# alert %></p>
      						</div>
	      </div>
	    </div>
	  </div>
</div>

app/views/routes/index.html.erb
<div class="container-fluid routes index">
	<div class="row background-base">
		<%= render "partials/div_left" %>
		<div class="col-md-10 div-basic-right">
			<div class="row">
				<center><h1> Rutas </h1></center>
				<div class="col-md-2">

					<div class="row">
						<a href='#' id='geolocate' class='btn btn-default btn-mapbox-default'>Mi posición</a>
					</div>
					<div class="row" id="btn-mostrar-tabla">
						<a href='#' class='btn btn-default btn-mapbox-default btn-mostrar-tabla'>Mostrar en tabla</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-mostrar-mapa'>Mostrar en mapa</a>
					</div>


					<div class="row">
						<p class="text-pordificultad">Filtrar por dificultad:</p>
					</div>
					
					<div class="row" data-no-turbolink>
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-dificultad' data-difficulty="Principiante">Principiante</a>
						<%# link_to "Principiante", filter_routes_path(Route, :difficulty => "Principiante"), class: "btn btn-default btn-mapbox-default" %>
					</div>
				
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-dificultad' data-difficulty="Intermedia">Intermedia</a>
						<%# link_to "Intermedia", filter_difficulty_path(Route, :difficulty => "Intermedia"), class: "btn btn-default btn-mapbox-default" %>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-dificultad' data-difficulty="Dificil">Dificil</a>
						<%# link_to "Todos", routes_path, class: "btn btn-default btn-mapbox-default" %>
					</div>	

					<div class="row">
						<%= link_to "Todos", routes_path, class: "btn btn-default btn-mapbox-default" %>
					</div>

					<div class="row">
						<p class="text-pordificultad">Filtrar por cercanía:</p>
					</div>
					<div class="row">
						<a href='#' id="test" class='btn btn-default btn-mapbox-default btn-filtrar-distancia' data-distance="1000">< 1 km</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-distancia' data-distance="2000">< 2 km</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-distancia' data-distance="3000">< 3 km</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-distancia' data-distance="4000">< 4 km</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default btn-filtrar-distancia' data-distance="5000">< 5 km</a>
					</div>	

				</div>
				<div class="col-md-10 rutas-index">
					<div id='map'></div>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/routes/show.html.erb
<div class="container-fluid routes show">
	<div class="row background-base">
		<%= render "partials/div_left" %>
		<div class="col-md-10 div-basic-right">
			<center><h1> <%= @route.name %> </h1></center>
				<div class="col-md-2">

					<div class="row route-info-panel">
						<p><u>Lugar:</u> <b><%= @route.location %></b></p>
						<p><u>Dificultad:</u> <b><%= @route.difficulty %></b></p>
						<p><u>Distancia (km):</u> <b>10km.</b></p>
					</div>

					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default'>Mostrar recorrido</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default'>Elevación</a>
					</div>
					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default'>Tiempo</a>
					</div>

					<div class="row">
						<a href='#' class='btn btn-default btn-mapbox-default'>Añadir historial</a>
					</div>

				</div>

				<div class="col-md-10">
					<div id='map'></div>
				</div>

		</div>
	</div>
</div>